version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: church_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/church_finance
      SECRET_KEY: your-secret-key-here
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: